### ISSUE TITLE
AWS 사용 가능 HDD 용량 문제...

### ISSUE THREAD

**Issue by winterlood** [22hours/WEB#1]
현재 진행 상황
---

우선,  UBUNTU Server EC2 instnace 생성완료 및,

HTTP/ HTTPS/ Ipv4 echo 응답 / TCP port : 50000

인바운드 규칙 활성화 완료.

Ubunut를 선택한 이유 : 언제든 소스파일을 vi로 편집하고, guest로 접근하여도

수정가능, -> 동시 개발 가능

issue
---
1.
ubuntu server os를 사용하는것이 최적이라고 생각듦 허나,

2개의 ec2 인스턴스를 사용할 경우, 한달 15일 밖에 사용할 수 없음...

현재 aws로 진행하고 있는 작업이 존재하여, 2개의 ec2를 돌리는것은 어려워 보임

> 한명이 프리티어를 긁어준다면 정말 고마울듯...

2.
windows server로 진행할 경우...

AWS free-tier에서 제공하는 EC2 인스턴스를 사용할 경우,

free-tire이므로, 굉장히 낮은 HDD를 제공하므로, Visual code의 설치가 매우 꺼려짐

혹시 exe파일 형태로 배포될 수 있는지 ????

**Comment by jongwuner** [comment]
## Issue에 대한 궁금증 및 의견
1. 1년 ubuntu or Window EC2 인스턴스 1개(hdd 10기가 등 서버운영정도의  사양) 가격이 어느정도 되나요? 
 ** 이거 프리티어 할 수야 있긴한데, 장기적으로 봤을 때, 22Hours 서비스용 계정은 일관적으로 한군데서 관리하는게 맞지 않나 싶어서, 난 개인적으로 돈이 들더라도 결제를 하고 싶음.

2. 운영만 할꺼면 걍 Node.js와 React.js만 설치하면 되겠지만, (exe파일 형태로 배포하는 격)
해당 ec2인스턴스에서 유지보수를 할 예정인데, IDE 설치 안될정도면 이건 좀 제한됨. 용량을 늘려야겠죠. 

## 결론
프리티어의 바운더리에서는 벗어나자. 위대한 일들을 할 사람인데.
돈이야 쓰면 되지.
저도 같이 알아보겠음.

**Comment by jongwuner** [comment]
## 19.10.27 정환이랑 통화하고나서

1. A계정의 EC2를 B계정을 통해서도 접속하다는 사실을 알고나서, -> 다민이가 프리티어 긁어도 무방. 

2. 새로운 EC2에 우분투 깔아주면, 내가 거기에서 Node.js, React.js 세팅하겠음. 

이상 끝.
